In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns
import pandas as pd

# 업로드된 파일 경로
file_path = "C:/Users/jinwo/AI/iris.csv"

# CSV 파일 읽기
df = pd.read_csv(file_path)

# 데이터 확인
print(df.head())  # 상위 5개 데이터 확인
print(df.columns)  # 컬럼명 확인

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Name'], dtype='object')


In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Name(품종) 컬럼을 숫자로 변환
le = LabelEncoder()
df["Label"] = le.fit_transform(df["Name"])

# 입력(X)와 출력(y) 분리
X = df.drop(columns=["Name", "Label"])  # 입력값
y = df["Label"]  # 타겟값

# 데이터 분할 (80% 훈련, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# 데이터 크기 확인
print(f"훈련 데이터 크기: {X_train.shape}, 테스트 데이터 크기: {X_test.shape}")

훈련 데이터 크기: (112, 4), 테스트 데이터 크기: (38, 4)


In [5]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)
pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(f"Accuracy: {accuracy_score(y_test, pred_svm):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
Accuracy: 1.0000
Confusion Matrix:
 [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
